### ISSUE TITLE
Getting problems when replacing string with several $ characters

### ISSUE THREAD

**Issue by dbulgakov** [bluwy/substitute-string-action#3]
Hi there!

When trying to replace a string which contains n sequential $ characters, I get the output with n - 1 $ characters  

For example

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: bluwy/substitute-string-action@v1
      id: sub
      with:
        _input-text: 'Hello World!'
        World: Wo$$rld
    - run: echo ${{ steps.sub.outputs.result }}
```
    
Results to "Hello Wo$rld!" as output

Is there any way to fix that?
